# Generated by Django 2.1.1 on 2018-09-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180914_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
