# Generated by Django 2.1.1 on 2018-09-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20180914_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'prywatny'), (1, 'domowy'), (2, 'służbowy')], default=0),
        ),
        migrations.AlterField(
            model_name='tnumber',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'prywatny'), (1, 'domowy'), (2, 'służbowy')], default=0),
        ),
    ]
