# Generated by Django 2.1.1 on 2018-09-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20180915_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnumber',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
