# Generated by Django 2.1.1 on 2018-09-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20180915_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnumber',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
